spring:
  jpa:
    open-in-view : false
grpc:
  client:
    exchange:
      address: 'static://127.0.0.1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext